CREATE DATABASE CASTELLO_RELACIONAMENTO

USE CASTELLO_RELACIONAMENTO

CREATE TABLE PRODUTO (
    ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_PRODUTO VARCHAR(100) NOT NULL

);

CREATE TABLE ESTOQUE (
    ID_ESTOQUE INT AUTO_INCREMENT PRIMARY KEY,
    ID_PRODUTO INT NOT NULL UNIQUE,
    QUANTIDADE INT NOT NULL,
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
);

CREATE TABLE CLIENTES (
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOME_CLIENTE VARCHAR(60) NOT NULL
);

CREATE TABLE PEDIDOS(
    ID_PEDIDOS INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE INT NOT NULL,
    DATA_PEDIDO DATETIME NOT NULL,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

CREATE TABLE FORNECEDORES (
    ID_FORNECEDOR INT AUTO_INCREMENT PRIMARY KEY,
    NOME_FORNECEDOR VARCHAR(60) NOT NULL
);

CREATE TABLE FORNECEDOR_PRODUTO (
    ID_FORNECEDOR INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    PRIMARY KEY (ID_FORNECEDOR, ID_PRODUTO),
    FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDORES(ID_FORNECEDOR),
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
);


SELECT * FROM PRODUTO;

INSERT INTO PRODUTO (NOME_PRODUTO) VALUES ('Camiseta')

DROP TABLE FORNECEDORES;

-- Desafio da cardinalidade.
-- Identifique a cardinalidade e justifique.

-- 1 Q.

-- CATEGORIA -- PERTENCE -- PRODUTO
1,N                         1,1

-- 2 Q.
--FUNCIONÁRIO -- REGISTRA -- PEDIDOS
1,N                           1,1

-- 3 Q.
--FONECEDOR -- FORNECE -- PRODUTO
1,N                        1,N

4 Q. 
-- MESA -- VINCULA -- RESERVA
0,N                    1,1

5 Q.
-- PEDIDO -- POSSUI -- ITENS
1,N                     1,N
