-- Active: 1788268411059@@127.0.0.1@3306@smartcoffe_dml_livia
--- SMART COFFE BASE DE DADOS - DML 
--- EXECUTE SEMPRE QUE QUISER RESTAURAR A AULA

DROP DATABASE IF EXISTS  SMARTCOFFE_DML_LIVIA;
CREATE DATABASE SMARTCOFFE_DML_LIVIA;
USE SMARTCOFFE_DML_LIVIA;

--- TABELAS 
CREATE TABLE CLIENTE  (
    ID_CLIENTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL, 
    EMAIL VARCHAR(120) UNIQUE,
    TELEFONE  VARCHAR(15),
    CIDADE VARCHAR(60) NOT NULL,
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE CATEGORIA (
ID_CATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
NOME_CATEGORIA VARCHAR(60) NOT NULL UNIQUE
);

CREATE TABLE PRODUTO (
ID_PRODUTO INT PRIMARY KEY AUTO_INCREMENT,
NOME_PRODUTO VARCHAR(100) NOT NULL,
PRECO DECIMAL(10,2) NOT NULL,
ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
ID_CATEGORIA INT NOT NULL,
-- REFERÊNCIA DA NOMENCLATURA DE FOREIGN KEY, SEMPRE ACRESCENTAR ESSE TIPO DE DADO
CONSTRAINT FK_PRODUTP_CATEGORIA FOREIGN KEY (ID_CATEGORIA)
REFERENCES CATEGORIA(ID_CATEGORIA)
);

CREATE TABLE PEDIDO (
ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
DATA_PEDIDO DATETIME NOT NULL,
STATUS_PEDIDO ENUM('ABERTO', 'PREPARADO', 'FINALIZADO', 'CANCELADO') NOT NULL,
VALOR_TOTAL DECIMAL(10,2) NOT NULL DEFAULT 0.00,
ID_CLIENTE INT NOT NULL,
CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (ID_CLIENTE)
REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE TABLE ITEM_PEDIDO (
ID_ITEM INT PRIMARY KEY AUTO_INCREMENT,
ID_PEDIDO INT NOT NULL,
ID_PRODUTO INT NOT NULL,
QUANTIDADE INT NOT NULL,
PRECO_UNITARIO DECIMAL (10,2) NOT NULL,
OBSERVACAO VARCHAR(150),
CONSTRAINT FK_ITEM_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES 
PEDIDO (ID_PEDIDO),
CONSTRAINT FK_ITEM_PRODUTO FOREIGN KEY (ID_PRODUTO)
REFERENCES PRODUTO (ID_PRODUTO)
);

CREATE TABLE FORMA_PAGAMENTO (
ID_FORMA_PAGAMENTO INT PRIMARY KEY AUTO_INCREMENT,
DESCRICAO VARCHAR(40) NOT NULL
);

CREATE TABLE PAGAMENTO (
ID_PAGAMENTO INT PRIMARY KEY AUTO_INCREMENT,
ID_PEDIDO INT NOT NULL,
ID_FORMA_PAGAMENTO INT NOT NULL,
VALOR DECIMAL(10,2) NOT NULL,
DATA_PAGAMENTO DATETIME,
CONSTRAINT FK_PAGAMENTO_PEDIDO FOREIGN KEY (ID_PEDIDO) -- SEMPRE QUE HOUVER RELAÇÃO ENTRE DUAS ENTIDADES
REFERENCES PEDIDO (ID_PEDIDO),
CONSTRAINT FK_FORMA_PAGAMENTO FOREIGN KEY
(ID_FORMA_PAGAMENTO) REFERENCES FORMA_PAGAMENTO
(ID_FORMA_PAGAMENTO)
);

-- INSERÇÃO DE DADOS
INSERT INTO CLIENTE (NOME, EMAIL
,TELEFONE, CIDADE, ATIVO, DATA_CADASTRO) VALUES
('LILLY','LIRIO090909@GMAIL.COM','19 98121-5360', 'LIMEIRA', TRUE, NULL),
('HAGRID','HAGRID@GMAIL.COM','19 95678-5687', 'LIMEIRA', TRUE, NULL),
('DRACO MALFOY','MALVADINHO04@GMAIL.COM','19 66666-666', 'RIO CLARO', TRUE, NULL);
SELECT * FROM CLIENTE;

INSERT INTO CATEGORIA (NOME_CATEGORIA) VALUES
('Cerveja Amanteigada'),
('Suco de Abóbora'),
('Sapinhos de Chocolate'),
('Varinhas de Alcaçuz'),
('Pastéis de Abóbora');


INSERT INTO PRODUTO (NOME_PRODUTO, PRECO, ATIVO, ID_CATEGORIA) VALUES
('Cerveja Amanteigada', 500.00, TRUE, 1),
('Suco de Abóbora', 35.00, TRUE, 2),
('Sapinhos de Chocolate', 10.00, TRUE, 3),
('Varinhas de Alcaçuz', 70.00, TRUE, 4),
('Pastéis de Abóbora', 105.00, TRUE, 5)  ;                                 

INSERT INTO  PEDIDO(DATA_PEDIDO, STATUS, VALOR_TOTAL, ID_CLIENTE) VALUES
(NOW(), 'ABERTO', 0.00, 1),
(NOW(), 'CANCELADO', 0.00, 2),
(NOW(), 'FINALIZADO', 0.00, 3),
(NOW(), 'ABERTO', 0.00, 4);

SET @PEDIDO = LAST_INSERT_ID();
SELECT @PEDIDO;

INSERT INTO item_pedido (id_pedido, id_produto, quantidade, preco_unitario, observacao) VALUES
(1,1,1,7.00,NULL),(1,9,1,9.00,NULL),(2,4,2,13.00,'Sem canela'),
(3,7,1,18.00,NULL),(4,5,1,15.50,NULL),(4,16,1,20.00,NULL),
(5,16,1,20.00,NULL),(6,4,1,13.00,NULL),(6,7,1,18.00,NULL),
(7,6,2,14.00,NULL),(8,14,2,16.00,NULL),(8,12,2,6.00,NULL),
(9,4,1,13.00,NULL),(10,3,2,9.50,NULL),(10,16,1,20.00,NULL);
SELECT * FROM ITEM_PEDIDO;

INSERT INTO FORMA_PAGAMENTO(DESCRICAO) VALUES
('DINHEIRO'),
('CARTÃO DE CRÉDITO'),
('CARTÃO DE DÉBITO'),
('PIX');

INSERT INTO pagamento (id_pedido, id_forma_pagamento, valor, data_pagamento) VALUES
(1,2,16.00,'2026-09-01 08:20:00'),(2,4,26.00,'2026-09-01 09:40:00'),
(4,3,35.50,'2026-09-03 14:20:00'),(5,2,20.00,'2026-09-04 16:45:00'),
(7,1,28.00,'2026-09-06 09:00:00'),(8,3,30.00,'2026-09-07 17:30:00'),
(8,2,14.00,'2026-09-07 17:31:00'),(10,2,39.00,'2026-09-09 09:50:00');

-- UPDATE OU ATUALIZAÇÕES DE DADOS
-- EX1
UPDATE cliente
SET TELEFONE = '19992527920',
WHERE ID_CLIENTE = 3;
-- DETERMINAR O COMANDO WHERE SEMPRE
--CONSULTAR INFORMAÇÕES NO BD
SELECT * FROM CLIENTE;

-- EX2 -- ATUALIZANDO VÁRIOS CAMPOS
UPDATE cliente
SET TELEFONE = '19 98121-5360'
WHERE ID_CLIENTE = 2;

-- EX3 -- ATUALIZANDO VÁRIOS REGISTROS
UPDATE produto
SET PRECO = PRECO * 1.05
WHERE ID_CATEGORIA = 1;

-- EX4 -- ATUALIZANDO SEM WHERE
-- UPDATE PRODUTO
--SET PRECO = 1.00;
-- CUIDADO AO ULTILIZAR ESSA LINHA

-- EX5 -- ATUALIZANDO CONDICIONAIS
UPDATE PRODUTO
SET PRECO = CASE 
    WHEN PRECO < 10 THEN PRECO * 1.10  
    ELSE PRECO * 1.05 
END
WHERE ATIVO = TRUE;

-- EX6 -- ATUALIZANDO PARA NULL
UPDATE cliente 
SET TELEFONE = NULL
WHERE ID_CLIENTE = 5;
-- ATUALIZAÇÕES OU MODIFICAÇÃO E DADOS

-- EX1 -- EXCLUIR REGISTROS OU DADOS
DELETE FROM cliente
WHERE ID_CLIENTE = 2;

-- LIMPAR TABELA OU REMOVER REGISTROS
TRUNCATE TABLE CLIENTE;


-- EX2 -- EXCLUIR REGISTROS COM ESTRUTURA LÓGICA
UPDATE PRODUTO
SET ATIVO = FALSE
WHERE ID_PRODUTO = 12; 

UPDATE CLIENTE
SET ATIVO = FALSE
WHERE ID_CLIENTE = 8;

-- MENSAGEM DE SUCESSO
SELECT 'BANCO DE DADOS SMARTCOFFE_DML_LIVIA CRIADO COM SUCESSO!' AS mensagem;

