-- Comandos para criar banco de dados
CREATE DATABASE COFFE_LILLY;

CREATE DATABASE COFFE_LILLY2;

-- Comandos para apagar Bnaco de Dados
DROP DATABASE COFFE_LILLY2;

-- COMANDO PARA ATIVAR BANCO DE DADOS
USE COFFE_LILLY;

-- MOSTRAR TABELAS NO BANCO DE DADOS
SHOW TABLES;

-- COMANDO PARA CRIAR TABELAS
CREATE TABLE COFFE(
ID_COFFE INT auto_increment primary key,
Nome VARCHAR(60)  NOT NULL,
Telefone INT,
CPF VARCHAR(40)  NOT NULL,
Email VARCHAR(40)  NOT NULL,
Historico datetime
);

CREATE TABLE PRODUTOS (
ID_PRODUTO INT auto_increment primary key,
MARCA VARCHAR(14) NOT NULL,
QUANTIDADE VARCHAR(60) NOT NULL,
PESO CHAR(50),
PREÇO DECIMAL(5,2),
STATUS_PRODUTOS BOOLEAN
);
-- COMANDOS PARA ALTERAR INFORMAÇÕES
-- ADICIONAE UM NOVO ATRIBUTO
ALTER TABLE COFFE ADD ENDEREÇO VARCHAR(20);

-- RENOMEAR O NOME DO ATRIBUTO
ALTER TABLE COFFE MODIFY ENDEREÇO VARCHAR(20);

-- RENOMEAR O NOME DO ATRIBUTO
-- ALTER TABLE COFFE CHANGE ENDEREÇO LOJA(20);

-- RENOMEAR TABELAS
ALTER TABLE coffe_lilly RENAME TO COFFE;

-- EXCLUIR ATRIBUTO
ALTER TABLE COFFE DROP COLUMN Telefone;

-- LIMPAR  DADOS DA TABELA
TRUNCATE TABLE COFFE